// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID        int64            `json:"id"`
	Url       string           `json:"url"`
	Short     string           `json:"short"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
