// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: urls.sql

package db

import (
	"context"
)

const createURL = `-- name: CreateURL :one
insert into urls (url, short, created_at)
values ($1, $2, now())
returning id, url, short, created_at
`

type CreateURLParams struct {
	Url   string `json:"url"`
	Short string `json:"short"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL, arg.Url, arg.Short)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Short,
		&i.CreatedAt,
	)
	return i, err
}
